TAGGED_REWARD = (100, -100)
NOT_TAGGED_REWARD = (0, 0)

MOVE_REWARD = (-0.05, 0.05)
END_REWARD = (0, 0)
COLLISION_REWARD = 0
DISTANCE_REWARD_FACTOR = 0.0
MOVE_TOWARDS_REWARD = (0, 0)
MOVE_AWAY_REWARD = (0, 0)

TERMINATED_REWARD = 0
TRUNCATED_REWARD = (0, 0)

WRONG_GRAB_RELEASE_REWARD = 0
