TAGGED_REWARD = (1, -1)
NOT_TAGGED_REWARD = (0, 0)

MOVE_REWARD = (0, 0)
END_REWARD = (0, 0)
COLLISION_REWARD = -0.5
DISTANCE_REWARD_FACTOR = 0.5
MOVE_TOWARDS_REWARD = (0.1, -0.1)
MOVE_AWAY_REWARD = (-0.1, 0.1)

TERMINATED_REWARD = 0
TRUNCATED_REWARD = (0, 0)

WRONG_GRAB_RELEASE_REWARD = 0
